# Generated by Django 3.2.9 on 2021-11-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
