# Generated by Django 3.2.6 on 2021-11-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twt', '0002_alter_tweet_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(default='default title', max_length=400),
            preserve_default=False,
        ),
    ]
