# Generated by Django 3.2.9 on 2021-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twt', '0003_tweet_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['time_crate'], 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='time_crate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Заголовок'),
        ),
    ]
