# Generated by Django 3.2.9 on 2021-11-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twt', '0004_auto_20211112_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-time_crate'], 'verbose_name_plural': 'Посты'},
        ),
    ]
