# Generated by Django 4.0.2 on 2022-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
