# Generated by Django 4.0.2 on 2022-02-15 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carlist_car_name_alter_carlist_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carlist',
            options={'ordering': ['time_create'], 'verbose_name': 'Объявлениe', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='price',
        ),
        migrations.AddField(
            model_name='carlist',
            name='year',
            field=models.PositiveIntegerField(default=1955, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
