# Generated by Django 4.0.2 on 2022-02-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carlist_options_remove_carlist_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carlist',
            options={'ordering': ['time_create'], 'verbose_name': 'Статью', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Тип кузова'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_create'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
